config/routes.rb
Rails.application.routes.draw do
  resources :cars, only: %i[index new create show update]
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  root "cars#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/car.rb
class Car < ApplicationRecord
  has_one_attached :photo
  validates :plate, presence: true, uniqueness: true

  before_validation :upcase_plate

  def upcase_plate
    # Elimina espacios y convierte a mayúsculas
    self.plate = plate.strip.upcase
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Only allow modern browsers supporting webp images, web push, badges, import maps, CSS nesting, and CSS :has.
  allow_browser versions: :modern
end

app/controllers/cars_controller.rb
class CarsController < ApplicationController
  def index
    if params[:search].present?
      @cars = Car.where("plate LIKE ?", "%#{params[:search].upcase}%").order(:plate)
    else
      @cars = Car.order(:plate).all
    end
  end

  def new
    @car = Car.new
  end

  def create
    @car = Car.new(params.require(:car).permit(:plate, :brand, :model, :color, :city, :address, :photo))
    if @car.save
      redirect_to @car
    elsif colision = Car.find_by(plate: @car.plate)
      redirect_to colision
    else
      render :new
    end
  end

  def show
    @car = Car.find(params[:id])
    if @car.photo.attached?
      begin
        Tempfile.open(['photo', '.jpg']) do |file|
          file.binmode
          file.write(@car.photo.download)
          file.rewind
          exif = MiniExiftool.new(file.path)
          @latitude_dms = exif.GPSLatitude
          latitude_ref = exif.GPSLatitudeRef
          @longitude_dms = exif.GPSLongitude
          longitude_ref = exif.GPSLongitudeRef

          @latitude = dms_to_decimal(@latitude_dms, latitude_ref)
          @longitude = dms_to_decimal(@longitude_dms, longitude_ref)  
        end
      rescue => e
        @latitude = nil
        @longitude = nil
        Rails.logger.error(e)
      end
    end
  end

  def update
    @car = Car.find(params[:id])
    if @car.update(params.require(:car).permit(:photo))
      redirect_to @car
    else
      render :show
    end
  end

  private

  def dms_to_decimal(dms, direction)
    parts = dms.scan(/(\d+)\D+(\d+)\D+([\d.]+)/).flatten
    degrees = parts[0].to_f
    minutes = parts[1].to_f
    seconds = parts[2].to_f
  
    decimal = degrees + (minutes / 60) + (seconds / 3600)
    decimal *= -1 if %w[S W South West].include?(direction)
    decimal
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cars_helper.rb
module CarsHelper
end

app/views/cars/index.html.erb
<h1 class="h2 mb-3">Registro de vehículos afectados por la dana</h1>

<%= form_with url: cars_path, method: :get, local: true do %>
  <div class="mb-3 d-flex align-items-center">
    <%= label_tag :search, "Buscar por matrícula:", class: "form-label me-2" %>
    <%= text_field_tag :search, params[:search], class: "form-control me-2" %>
    <%= submit_tag "Buscar", class: "btn btn-primary" %>
  </div>
<% end %>

<div class="table-responsive">
  <table class="table">
    <thead class="table-light">
      <tr>
        <th>Matrícula</th>
        <th>Marca</th>
        <th>Modelo</th>
        <th>Color</th>
        <th>Municipio</th>
        <th>Dirección</th>
        <th>Fecha de registro</th>
      </tr>
    </thead>
    <tbody>
      <% @cars.each do |car| %>
        <tr>
          <td><%= link_to car.plate, car %></td>
          <td><%= car.brand %></td>
          <td><%= car.model %></td>
          <td><%= car.color %></td>
          <td><%= car.city %></td>
          <td><%= car.address %></td>
          <td><%= l car.created_at, format: :long %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/cars/new.html.erb
<div class="container">
  <h1 class="h2">Nuevo vehículo</h1>
  <%= form_with model: @car do |f| %>
    <div class="mb-3">
      <%= f.label :plate, "Matrícula", class: "form-label" %>
      <%= f.text_field :plate, required: true, class: "form-control" %>
    </div>
    <div class="mb-3">
      <%= f.label :brand, "Marca", class: "form-label" %>
      <%= f.text_field :brand, class: "form-control" %>
    </div>
    <div class="mb-3">
      <%= f.label :model, "Modelo", class: "form-label" %>
      <%= f.text_field :model, class: "form-control" %>
    </div>
    <div class="mb-3">
      <%= f.label :color, "Color", class: "form-label" %>
      <%= f.text_field :color, class: "form-control" %>
    </div>
    <div class="mb-3">
      <%= f.label :city, "Municipio", class: "form-label"%>
      <%= f.select :city, ["Chiva", "Cheste", "Aldaya", "Alacuas", "Torrent", "Picanya", "Paiporta", "Alfafar", "Massanasa", "Catarroja", "La albufera"].sort, {}, class: "form-select" %>
    </div>
    <div class="mb-3">
      <%= f.label :address, "Dirección", class: "form-label" %>
      <%= f.text_field :address, class: "form-control" %>
    </div>
    <div class="mb-3">
      <%= f.label :photo, "Fotografía", class: "form-label" %>
      <%= f.file_field :photo, class: "form-control" %>
    </div>
    <%= f.submit "Registrar vehículo", class: "btn btn-success" %>
  <% end %>
</div>

app/views/cars/show.html.erb
<%= link_to "Volver", cars_path %>

<h1 class="h2"><%= @car.plate %></h1>

<table class="table">
  <thead>
    <tr>
      <th>Matrícula</th>
      <th>Marca</th>
      <th>Modelo</th>
      <th>Color</th>
      <th>Municipio</th>
      <th>Dirección</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td><%= @car.plate %></td>
      <td><%= @car.brand %></td>
      <td><%= @car.model %></td>
      <td><%= @car.color %></td>
      <td><%= @car.city %></td>
      <td><%= @car.address %></td>
    </tr>
  </tbody>
</table>

<h6>Foto</h6>
<% if @car.photo.attached? %>
  <%= link_to @car.photo, target: "_blank" do %>
    <%= image_tag @car.photo.variant(resize_to_limit: [500, 500]) %>
  <% end %>

  <h6>Ubicación</h6>
  <% if @latitude && @longitude %>
    <p>Coordenadas: <%= @latitude_dms %>, <%= @longitude_dms %> (<%= @latitude %>,<%= @longitude %>)</p>
    <div id="map" style="height: 500px;"></div>
    <script>
      document.addEventListener("DOMContentLoaded", function() {
        var map = L.map('map').setView([<%= @latitude %>, <%= @longitude %>], 13);
        L.tileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png', {
          attribution: '&copy; <a href="https://www.openstreetmap.org/copyright">OpenStreetMap</a> contributors'
        }).addTo(map);
        L.marker([<%= @latitude %>, <%= @longitude %>]).addTo(map)
          .bindPopup('Localización de la fotografía')
          .openPopup();
      });
    </script>
  <% else %>
    <p>No hay ubicación</p>
  <% end %>
<% else %>
  <p>Añade una foto con metadatos de geolocalización para ayudar a localizar el vehículo</p>
  <%= form_with model: @car do |f| %>
    <div class="mb-3">
      <%= f.label :photo, "Fotografía", class: "form-label" %>
      <%= f.file_field :photo, class: "form-control" %>
    </div>
    <%= f.submit "Añadir fotografía", class: "btn btn-success" %>
  <% end %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for(:title) || "Vehículos afectados por la DANA" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>

    <link rel="manifest" href="/manifest.json">
    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <link rel="stylesheet" href="https://unpkg.com/leaflet@1.7.1/dist/leaflet.css" />
    <script src="https://unpkg.com/leaflet@1.7.1/dist/leaflet.js"></script>
  </head>

  <body>
    <nav class="navbar bg-body-secondary border-bottom">
      <div class="container-fluid">
        <%= link_to "Vehículos DANA", root_path, class: "fw-bold navbar-brand" %>
        <%= link_to "Registrar nuevo vehículo", new_car_path, class: "btn btn-primary" %>
      </div>
    </nav>
    <div class="container-fluid my-3">
      <div class="alert alert-info">
        Puedes encontrar un proyecto alternativo para registrar y localizar vehículos en <a href="https://tucochedana.es">https://tucochedana.es</a>.
      </div>
      <%= yield %>
    </div>
  </body>
</html>